### login maria
POST http://localhost:8080/login
content-type: application/json

{
  "username": "jordi",
  "password": "password123"
}
> {%
    client.global.set("auth_token", response.headers.valueOf("Authorization"));
    client.log("token: " + response.headers.valueOf("Authorization"));
%}

###
GET http://localhost:8080/teaching/unregistered

###
GET http://localhost:8080/teaching/principal
Authorization: {{auth_token}}

### get josep
GET http://localhost:8080/profiles/josep@tecnocampus.cat
Authorization: {{auth_token}}

### get me
GET http://localhost:8080/profiles/me
Authorization: {{auth_token}}

### get my candidates
GET http://localhost:8080/profiles/me/candidates
Authorization: {{auth_token}}


### get all profiles
GET http://localhost:8080/profiles
Authorization: {{auth_token}}

### get candidates by email
GET http://localhost:8080/profiles/josep@tecnocampus.cat/candidates

###
GET http://localhost:8080/likes

###
GET http://localhost:8080/likesInterface


### post profile
POST http://localhost:8080/profiles
content-type: application/json
Authorization: {{auth_token}}

{
	"email": "manuu@tecnocampus.cat",
	"nickname": "Manuell",
	"gender": "Man",
	"attraction": "Woman",
	"passion": "Sport"
}

### post incorrect profile
POST http://localhost:8080/profiles
content-type: application/json
Authorization: {{auth_token}}

{
  "email": "manuutecnocampus.cat",
  "nickname": "ll",
  "gender": "Man",
  "attraction": "Woman",
  "passion": "Sport"
}

### post like
POST http://localhost:8080/likes
content-type: application/json
Authorization: {{auth_token}}
{
  "origin" : "pepe@tecnocampus.cat",
  "targets": ["maria@tecnocampus.cat", "marta@tecnocampus.cat"]
}

### post like error origin
POST http://localhost:8080/likes
content-type: application/json
Authorization: {{auth_token}}
{
  "origin" : "error@tecnocampus.cat",
  "targets": ["maria@tecnocampus.cat", "marta@tecnocampus.cat"]
}

### post like error target
POST http://localhost:8080/likes
content-type: application/json
Authorization: {{auth_token}}
{
  "origin" : "pepe@tecnocampus.cat",
  "targets": ["maria@tecnocampus.cat", "error@tecnocampus.cat"]
}

### post profile as string
POST http://localhost:8080/teaching/profilesString
content-type: application/string
Authorization: {{auth_token}}
{
  "email": "manuu@tecnocampus.cat",
  "nickname": "Manuell",
  "gender": "Man",
  "attraction": "Woman",
  "passion": "Sport"
}

### get josep candidates
GET http://localhost:8080/profiles/josep@tecnocampus.cat/candidates
Authorization: {{auth_token}}

### get josep candidates
GET http://localhost:8080/profiles/error@tecnocampus.cat/candidates
Authorization: {{auth_token}}

### get int
GET http://localhost:8080/teaching/int/43
Authorization: {{auth_token}}